apiVersion: v2
name: openclaw-enterprise-computenest
description: ComputeNest packaging for OpenClaw Enterprise on Kubernetes
type: application
version: 0.1.7
appVersion: "a5cc0d75139f2c61dd148f8332a9167102fd9752"
